### ISSUE TITLE
Problema net framework

### ISSUE THREAD

**Issue by mkultimate** [samehb/HIDer#2]
When this application is launched, this error appears 

OS: windows 10 64Bits

![image](https://user-images.githubusercontent.com/16367065/41688022-e8054eba-74af-11e8-920e-7188e8c1a156.png)

![image](https://user-images.githubusercontent.com/16367065/41688033-00fd607e-74b0-11e8-83a1-16034de9c344.png)

![image](https://user-images.githubusercontent.com/16367065/41688062-14db9282-74b0-11e8-9220-d50b0a6be148.png)

**Comment by samehb** [comment]
Hi mkultimate, right click the .exe file for the application, and "Run as administrator."

**Comment by mkultimate** [comment]
thank you very much solved problem

**Comment by samehb** [comment]
You are welcome, mkultimate.
